version: '3'
services:
  server:
    build:
      context: .
    image: club_mileages
    ports:
      - "9900:9900"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/club
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: club
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      LC_COLLATE: "C"
      TZ: Asia/Seoul
    ports:
      - "5439:5432"
