version: '3'
services:
  server:
    build:
      context: .
    image: club_mileages
    ports:
      - "9900:9900"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/club
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
  db:
    image: mysql:5.7.32
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: club
      MYSQL_ROOT_HOST: "%"

    ports:
      - "3307:3306"
