version: '3'
services:
  server:
    build:
      context: .
    image: club_mileages
    ports:
      - "9900:9900"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/club?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: club
      MYSQL_PASSWORD: club
      MYSQL_DATABASE: club
      MYSQL_USER_HOST: "%"
    ports:
      - "3306:3306"
