spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/club?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    password: admin
    username: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true

server:
  port: 9900

springdoc:
  swagger-ui:
    path: swagger-ui.html
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health
